name: Build
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          java-version: 21
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@main
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew shadowJar

      - name: Upload
        uses: actions/upload-artifact@main
        with:
          name: build
          path: build/libs/HibiscusCommons-*.jar
